### ISSUE TITLE
CURIOSO!

### ISSUE THREAD

**Issue by doradoc1** [javix64/Scraping-Milanuncios#1]
Hola, me ha resultado curioso el uso del scraping para esta web. No te banean? En teoría están excluidas estas practicas en su política web. Me gustaría preguntarte algunas cosas mas ya que me parece muy practico.

**Comment by javix64** [comment]
Gracias @doradoc1 . En teoría y en práctica están excluidas. pero bueno, ésto a pequeña escala( es decir, solo una categoria y unas pocas paginas). No creo que me baneen, si baneran, tendría que poner un delay, para que fuera más "orgánico"
para preguntarme cosas tienes mi twitter https://twitter.com/javix64.
Cierro el issue.
